### ISSUE TITLE
(suggested fix) .net core support for IgnoreCertificateErrors

### ISSUE THREAD

**Issue by jmkinzer** [jchristn/RestWrapper#11]
Please note that
``ServicePointManager.ServerCertificateValidationCallback = ...``
doesn't appear to do anything in .net core. I was able to get the expected behavior via
``
                        handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => true;
``

**Comment by jchristn** [comment]
Thanks for this @jmkinzer - publishing an update to NuGet as v3.0.18: https://www.nuget.org/packages/RestWrapper/3.0.18

Please re-open if any issues
