### ISSUE TITLE
RestRequest.Send doesn't work properly. Content is not sent.

### ISSUE THREAD

**Issue by andrejzoz** [jchristn/RestWrapper#2]
Hi, I have some issue with yours wrapper. May be I'm wrong - but this didnt send any content at all:
```
            RestRequest req = new RestRequest(
                @"http://127.0.0.1:9000", 
                HttpMethod.GET,
                null,                     // Dictionary<string, string> headers
                "text/plain");                    // Content type 

            RestResponse resp = req.Send("TEST"));
```
Server got an empty request.
Or I'm wrong and GET will not send anything? I have to use PUT?
WBR,
Andrej

**Comment by jchristn** [comment]
Hi @andrejzoz that is correct, RestWrapper will not send a content body on a GET or HEAD request.  You would need to use PUT, POST, or DELETE for that.  Cheers, Joel
