### ISSUE TITLE
Remove json.net dependency

### ISSUE THREAD

**Issue by nhaberl** [jchristn/RestWrapper#6]
Hey, would be great to abstract the serialization library so it can be used the library of choice.

**Comment by jchristn** [comment]
Hi @nhaberl do you have a suggestion on what this implementation might look like?

**Comment by nhaberl** [comment]
Just abstract it to interface and deliver a default impl based on any .net integrated serializer.
I guess it is enough to add the interface as an optional cosntructor argument or set it as a global static property which can be accessed by any part of your code (or maybe a seoerate RestOptions type or so)

**Comment by jchristn** [comment]
Hi @nhaberl I'm very sorry it took forever to get to this.  I took your advice and did what you suggested.  Thank you for the suggestion!

NuGet: https://www.nuget.org/packages/RestWrapper/2.3.1
Commit: https://github.com/jchristn/RestWrapper/commit/248d34084a4b2bc50aa0582dc0121197823ac813
