### ISSUE TITLE
post request error http 500

### ISSUE THREAD

**Issue by lanwah** [jchristn/RestWrapper#8]
when you send a post requst , if content-type is passed by the Headers ,it will retun the http 500 error,code like this :
![image](https://user-images.githubusercontent.com/17949808/227450780-6297e030-495f-4e0c-8054-595b3e262540.png)

**Comment by lanwah** [comment]
can optimize 574 line code in RestRequest.cs like this ?
![image](https://user-images.githubusercontent.com/17949808/227720202-78109057-0bce-456d-a2b8-6a9172cb98ca.png)

**Comment by jchristn** [comment]
Please re-open if this doesn't address the issue!  Cheers

Commit: https://github.com/jchristn/RestWrapper/commit/3c4f086610fd6573c810fd17f52e351c2e5b2ef7
NuGet: https://www.nuget.org/packages/RestWrapper/2.3.2

**Comment by lanwah** [comment]
nice,update to 2.3.2 it work well.
